services:
  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    environment:
      PUID: ${USER_UID}
      PGID: ${USER_GID}
      TZ: ${TIMEZONE}
    volumes:
      - ./config:/config
      - /var/log:/var/log:ro
      - ../vaultwarden/vw-log:/remotelogs/vaultwarden:ro