services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
      DOMAIN: https://${VW_SUBDOMAIN}.{DOMAIN}
      SIGNUPS_ALLOWED: false
      LOG_FILE: /data/vaultwarden.log
      ADMIN_TOKEN: ${VW_ADMIN_TOKEN}
      PUSH_ENABLED: true
      PUSH_INSTALLATION_ID: ${VW_PUSH_INSTALLATION_ID}
      PUSH_INSTALLATION_KEY: ${VW_PUSH_INSTALLATION_KEY}
      PUSH_RELAY_URI: https://api.bitwarden.eu
      PUSH_IDENTITY_URI: https://identity.bitwarden.eu
    volumes:
      - ./vw-data:/data
      - ./vw-log/vaultwarden.log:/data/vaultwarden.log
    networks:
      - traefik-net
    labels:
      - traefik.enable=true

      - traefik.http.routers.vaultwarden-http.rule=Host(`${VW_SUBDOMAIN}.${PUBLIC_DOMAIN}`)
      - traefik.http.routers.vaultwarden-http.entrypoints=http
      - traefik.http.routers.vaultwarden-http.middlewares=redirect-https@file

      - traefik.http.routers.vaultwarden-https.rule=Host(`${VW_SUBDOMAIN}.${PUBLIC_DOMAIN}`)
      - traefik.http.routers.vaultwarden-https.entrypoints=https
      - traefik.http.routers.vaultwarden-https.tls=true
      - traefik.http.routers.vaultwarden-https.tls.certresolver=letsencrypt
      # Prevent access to admin panel from outside
      - traefik.http.routers.vaultwarden-https.middlewares=vaultwarden-admin-block
      - traefik.http.middlewares.vaultwarden-admin-block.redirectregex.regex=https://${VW_SUBDOMAIN}.${PUBLIC_DOMAIN}/admin/?.*
      - traefik.http.middlewares.vaultwarden-admin-block.redirectregex.replacement=https://${VW_SUBDOMAIN}.${PUBLIC_DOMAIN}
      - traefik.http.middlewares.vaultwarden-admin-block.redirectregex.permanent=true

      - traefik.http.routers.vaultwarden-local-http.rule=Host(`${VW_SUBDOMAIN}.${LOCAL_DOMAIN}`)
      - traefik.http.routers.vaultwarden-local-http.entrypoints=http
      - traefik.http.routers.vaultwarden-local-http.middlewares=redirect-https@file

      - traefik.http.routers.vaultwarden-local-https.rule=Host(`${VW_SUBDOMAIN}.${LOCAL_DOMAIN}`)
      - traefik.http.routers.vaultwarden-local-https.entrypoints=https
      - traefik.http.routers.vaultwarden-local-https.tls=true

networks:
  traefik-net:
    external: true
