services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
      DOMAIN: https://vaultwarden.{DOMAIN}
      SIGNUPS_ALLOWED: false
      LOG_FILE: /data/vaultwarden.log
      ADMIN_TOKEN: ${VW_ADMIN_TOKEN}
      PUSH_ENABLED: true
      PUSH_INSTALLATION_ID: ${VW_PUSH_INSTALLATION_ID}
      PUSH_INSTALLATION_KEY: ${VW_PUSH_INSTALLATION_KEY}
      PUSH_RELAY_URI: https://api.bitwarden.eu
      PUSH_IDENTITY_URI: https://identity.bitwarden.eu
    volumes:
      - ./vw-data:/data
      - ./vw-log/vaultwarden.log:/data/vaultwarden.log
    networks:
      - traefik-net
    labels:
      - traefik.enable=true

      - traefik.http.routers.vaultwarden-http.service=vaultwarden-http
      - traefik.http.services.vaultwarden-http.loadbalancer.server.port=80
      - traefik.http.middlewares.redirect-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-https.redirectscheme.permanent=true
      - traefik.http.routers.vaultwarden-http.middlewares=redirect-https
      - traefik.http.routers.vaultwarden-http.rule=Host(`vaultwarden.${DOMAIN}`)
      - traefik.http.routers.vaultwarden-http.entrypoints=http

      - traefik.http.routers.vaultwarden-https.service=vaultwarden-https
      - traefik.http.services.vaultwarden-https.loadbalancer.server.port=80
      - traefik.http.routers.vaultwarden-https.rule=Host(`vaultwarden.${DOMAIN}`)
      - traefik.http.routers.vaultwarden-https.entrypoints=https
      - traefik.http.routers.vaultwarden-https.tls=true
      - traefik.http.routers.vaultwarden-https.tls.certresolver=letsencrypt
      # Prevent admin access from outside
      - traefik.http.middlewares.vaultwarden-admin-block.redirectregex.regex=https://vaultwarden.${DOMAIN}/admin
      - traefik.http.middlewares.vaultwarden-admin-block.redirectregex.replacement=https://vaultwarden.${DOMAIN}
      - traefik.http.routers.vaultwarden-https.middlewares=vaultwarden-admin-block

      - traefik.http.routers.vaultwarden-local.service=vaultwarden-local
      - traefik.http.services.vaultwarden-local.loadbalancer.server.port=80
      - traefik.http.routers.vaultwarden-local.rule=Host(`vaultwarden.local`)
      - traefik.http.routers.vaultwarden-local.entrypoints=http

networks:
  traefik-net:
    external: true
