services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      TZ: ${TIMEZONE}
      WEBPASSWORD: ${PIHOLE_WEB_PASSWORD}
      WEBTHEME: default-dark
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    networks:
      traefik-net:
      pihole-net:
        ipv4_address: 172.0.0.2
    dns:
      - 127.0.0.11
      - 127.0.0.1
    extra_hosts:
      - ${TRAEFIK_SUBDOMAIN}.${LOCAL_DOMAIN}:${LOCAL_IP}
      - ${PIHOLE_SUBDOMAIN}.${LOCAL_DOMAIN}:${LOCAL_IP}
      - ${VW_SUBDOMAIN}.${LOCAL_DOMAIN}:${LOCAL_IP}

    labels:
      - traefik.enable=true
      - traefik.http.services.pihole.loadbalancer.server.port=80

      - traefik.http.routers.pihole-http.rule=Host(`${PIHOLE_SUBDOMAIN}.${LOCAL_DOMAIN}`)
      - traefik.http.routers.pihole-http.entrypoints=http
      - traefik.http.routers.pihole-http.middlewares=redirect-https@file

      - traefik.http.routers.pihole-https.service=pihole
      - traefik.http.routers.pihole-https.rule=Host(`${PIHOLE_SUBDOMAIN}.${LOCAL_DOMAIN}`)
      - traefik.http.routers.pihole-https.entrypoints=https
      - traefik.http.routers.pihole-https.tls=true
      # Auto redirect to admin panel
      - traefik.http.routers.pihole-https.middlewares=pihole-admin-redir
      - traefik.http.middlewares.pihole-admin-redir.redirectregex.regex=^https://${PIHOLE_SUBDOMAIN}.${LOCAL_DOMAIN}/?$$
      - traefik.http.middlewares.pihole-admin-redir.redirectregex.replacement=https://${PIHOLE_SUBDOMAIN}.${LOCAL_DOMAIN}/admin/
      - traefik.http.middlewares.pihole-admin-redir.redirectregex.permanent=true

networks:
  traefik-net:
    external: true

  pihole-net:
    name: pihole-net
    external: false
    ipam:
      config:
        - subnet: 172.0.0.0/24