services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      TZ: ${TIMEZONE}
      WEBPASSWORD: ${PIHOLE_WEB_PASSWORD}
      WEBTHEME: default-dark
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    networks:
      traefik-net:
      pihole-net:
        ipv4_address: 172.0.0.2
    dns:
      - ${PIHOLE_PUBLIC_DNS}
      - 127.0.0.11
    labels:
      - traefik.enable=true
      - traefik.http.services.pihole.loadbalancer.server.port=80
      - traefik.http.routers.pihole.rule=Host(`pihole.local`)
      - traefik.http.routers.pihole.entrypoints=http
      - traefik.http.middlewares.pihole-admin-redir.redirectregex.regex=^http://pihole.local/?$$
      - traefik.http.middlewares.pihole-admin-redir.redirectregex.replacement=http://pihole.local/admin/
      - traefik.http.routers.pihole.middlewares=pihole-admin-redir

networks:
  traefik-net:
    external: true

  pihole-net:
    name: pihole-net
    external: false
    ipam:
      config:
        - subnet: 172.0.0.0/24