services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      # - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik-net
      - --entrypoints.http.address=:80
      - --entryPoints.https.address=:443
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_LE_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --providers.file.directory=/etc/traefik/dynamic
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic:/etc/traefik/dynamic:ro
      - ./letsencrypt:/letsencrypt
      - ../local-cert/https:/certs
    networks:
      - traefik-net
    labels:
      - traefik.enable=true

      - traefik.http.routers.traefik-dash-http.rule=Host(`${TRAEFIK_SUBDOMAIN}.${LOCAL_DOMAIN}`)
      - traefik.http.routers.traefik-dash-http.entrypoints=http
      - traefik.http.routers.traefik-dash-http.middlewares=redirect-https@file

      - traefik.http.routers.traefik-dash-https.service=api@internal
      - traefik.http.routers.traefik-dash-https.rule=Host(`${TRAEFIK_SUBDOMAIN}.${LOCAL_DOMAIN}`)
      - traefik.http.routers.traefik-dash-https.entrypoints=https
      - traefik.http.routers.traefik-dash-https.tls=true
      - traefik.http.routers.traefik-dash-https.middlewares=traefik-dash-auth
      - traefik.http.middlewares.traefik-dash-auth.basicauth.users=${TRAEFIK_DASH_AUTH}

networks:
  traefik-net:
    external: false
    name: traefik-net