services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich
    restart: unless-stopped
    depends_on:
      - redis
      - database
    environment:
      TZ: ${TIMEZONE}
      DB_DATABASE_NAME: immich
      DB_USERNAME: postgres
      DB_PASSWORD: ${IMMICH_DB_PASSWORD}
    volumes:
      - ./library:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik-net
      - immich-net
    labels:
      - traefik.enable=true
      - traefik.http.services.immich.loadbalancer.server.port=2283

      - traefik.http.routers.immich-http.rule=Host(`${IMMICH_SUBDOMAIN}.${PUBLIC_DOMAIN}`)
      - traefik.http.routers.immich-http.entrypoints=http
      - traefik.http.routers.immich-http.middlewares=redirect-https@file

      - traefik.http.routers.immich-https.service=immich
      - traefik.http.routers.immich-https.rule=Host(`${IMMICH_SUBDOMAIN}.${PUBLIC_DOMAIN}`)
      - traefik.http.routers.immich-https.entrypoints=https
      - traefik.http.routers.immich-https.tls=true
      - traefik.http.routers.immich-https.tls.certresolver=letsencrypt


  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich-ml
    restart: unless-stopped
    volumes:
      - ./model_cache:/cache
    environment:
      TZ: ${TIMEZONE}
      DB_DATABASE_NAME: immich
      DB_USERNAME: postgres
      DB_PASSWORD: ${IMMICH_DB_PASSWORD}
    networks:
      - immich-net

  redis:
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    container_name: immich-redis
    restart: unless-stopped
    networks:
      - immich-net


  database:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    container_name: immich-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: immich
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ./db_data:/var/lib/postgresql/data
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    networks:
      - immich-net


networks:
  traefik-net:
    external: true
    name: traefik-net
  
  immich-net:
    name: immich-net
    external: false