services:
  website:
    build: ./notxia.github.io
    container_name: website
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - traefik.enable=true
      - traefik.http.services.website.loadbalancer.server.port=3000

      - traefik.http.routers.website-http.rule=Host(`${PUBLIC_DOMAIN}`)
      - traefik.http.routers.website-http.entrypoints=http
      - traefik.http.routers.website-http.middlewares=redirect-https@file

      - traefik.http.routers.website-https.service=website
      - traefik.http.routers.website-https.rule=Host(`${PUBLIC_DOMAIN}`)
      - traefik.http.routers.website-https.entrypoints=https
      - traefik.http.routers.website-https.tls=true
      - traefik.http.routers.website-https.tls.certresolver=letsencrypt

networks:
  traefik-net:
    external: true
